server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finalproject
    username: root
    password: 1001
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #use_sql_comments: true
  multipart:
    max-file-size : 10MB
    max-request-size : 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # about swagger


    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 326048053675-7v7efv49t2mcodd6n0qiddtj8ob785kf.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: = http://localhost:8080/login/oauth_google_check
            scope:
              - email
              - profileps://oauth2.googleapis.com


  






# image 업로드를위한 multipart
  servlet.multipart.max-file-size: 3MB
  servlet.multipart.max-request-size: 3MB


#본인 데스크톱 경로로 필수 변경
imgLocation: C:/Users/soh10/Desktop/Graduation/images/
uploadPath: file:///Users/soh10/Desktop/Graduation/images/
ttbkey : ttbwhddnr1122331414001

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

